apiVersion: v1
kind: Secret
metadata:
        name: {{ .Values.SecretTlsName }}
type: kubernetes.io/tls
data:
  # the data is abbreviated in this example
  tls.crt: |
        {{ .Values.SecretData.crt }}
  tls.key: |
        {{ .Values.SecretData.key }}
