apiVersion: v1
data:
  .dockerconfigjson: {{ .Values.SecretData.encryptedsecret }}
kind: Secret
metadata:
  name: {{ .Values.SecretRegistry }}
  namespace: {{ .Values.namespace }}
type: kubernetes.io/dockerconfigjson
